### ISSUE TITLE
Are there front boxes?

### ISSUE THREAD

**Issue by Bilgee** [karstenBehrendt/boxy#13]
Thank you for providing an awesome dataset. I saw the demo video on your website but there were any front boxes of cars. 
Does Boxy Dataset has only rear boxes and side polygons? Are there front boxes?

**Comment by karstenBehrendt** [comment]
The label instructions were to annotate vehicles that could affect our own vehicle's path. Since this dataset is mainly freeway driving, the annotations for a separated freeway should only cover vehicles rears and sides. (Assuming a front-facing camera and no vehicle going in the wrong direction.)

The vehicles are annotated using a rectangular bounding box (for front or rear) and a parallelogram for the sides. I don't think we explicitly labeled whether the rectangle described a front or rear, but I can be mistaken. It's been a few years.
