### ISSUE TITLE
Video fps is 8HZ but the paper claims 15HZ

### ISSUE THREAD

**Issue by xu-wang11** [karstenBehrendt/boxy#4]
Hi, I found that the dataset do not agree with what is described in your paper. In the paper, you said 

> "The data is stored at 15Hz"

 but the dataset I downloaded was recorded at 8HZ, only eight pictures in one second. Each picture is named by its timestamp, that’s how I tell the fps. Could you please explain about it?

**Comment by karstenBehrendt** [comment]
Sorry about the late response. I did not get any notifications for this repo, so I'm now going through all open issues.

Yes, I realize that was described too accurately. The data was collected at 15 fps but was only annotated at approximately 8fps. We collected about 500,000 images but only annotated 200,000 of them. 

We annotated every other image because the images may have been to similar at 15 fps. We also removed sections where the our vehicle was standing. The plan was to interpolate the annotations between frames. In the end, we opted to only provide the 200,000 human annotated images as part of this dataset.
